baseurl = "https://temu-ltky.github.io"
title = "Temu - Teekkareiden musiikki"
theme = "dimension"
languageCode = "fi-fi"
defaultContentLanguage = "fi"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  title = "Temu"
  description = """LAPPEENRANNAN TEKNILLISEN YLIOPISTON MUSIIKKIYHDISTYS TEMU RY.<br /> <a href="https://ltky.fi/">LTKY</a> Laserkatu 10 53850 Lappeenranta """
  logoimage = "/images/logo.png"
  copyright = "Temu"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/luttemury/"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/temu_ry/"

[languages]
[languages.fi]
languageName = "Suomeksi"
weight = 1
title = "Temu"

[languages.en]
languageName = "In English"
weight = 2
title = "Temu"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true